AdventureClub/urls.py
from django.conf import settings
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name="club"

urlpatterns = [
    # path('', views.home),
    path('', views.index, name='index'),

    # urls for user login/register/logout
    path('register/', views.RegisterClub, name='register'),
    path('signUp/', views.signup, name='signUp'),
    path('signOut/', views.signOut, name='signOut'),
    path('signIn/', views.signIn, name='signIn'),
    path('createEvent/',views.createEvent,name="createEvent"),
    path('myClubs/',views.myClubs,name="myClubs"),
    path('onGoingEvents/',views.onGoingEvents,name="events"),
    path('searchResults/',views.searchResults,name="searchResults"),
    path('detail/<int:pk>/',views.clubDetail,name="detail"),
    path('deleteClub/<int:pk>/',views.deleteClub.as_view(),name='deleteClub'),
    path('updateClub/<int:pk>/',views.updateClub.as_view(),name='updateClub'),
    path('popEvent/<int:pk>/',views.popedEvent,name='popEvent'),









    # urls for password reset
    # 1. for entering email to reset password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='AdventureClubs/password_reset.html'),
         name='password_reset'),

    # 2. for sending email to user who want to change password
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='AdventureClubs/password_reset_sent.html'),
         name='password_reset_done'),
    # 3. The link from email on which user clicks to reset password
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='AdventureClubs/password_reset_fill.html'),
         name='password_reset_confirm'),
    # 4. on successful reset of password
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='AdventureClubs/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sayahat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AdventureClub.urls')),
    path('club/',include('AdventureClub.urls')),

    # Added this for password reset fn
    path('', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AdventureClub/models.py
from django.db import models
from django.contrib.auth.models import User


class AdventureClub(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    club_name = models.CharField(max_length=50)
    contact = models.CharField(max_length=11, default='')
    email = models.EmailField(null=True)
    featured = models.BooleanField(default=False)
    club_image = models.ImageField(upload_to='AdventureClub/Club_Images', null=True)
    club_address = models.CharField(max_length=80)
    city = models.CharField(null=False, blank=False, default="", max_length=25)

    def __str__(self):
        return self.club_name


class AdventureEvent(models.Model):
    event_by = models.ForeignKey(AdventureClub, on_delete=models.CASCADE,default="")
    # event_by = models.CharField(max_length=50)
    title = models.CharField(max_length=80)
    overview = models.CharField(max_length=120, default='')
    image = models.ImageField(null=True, upload_to='AdventureClub/AdventureEventPics')
    featured = models.BooleanField(default=False)
    event_start_date = models.DateField()
    event_end_date = models.DateField()

    def __str__(self):
        return "Event- " + self.title


class EventDetails(models.Model):

    booked_event = models.ForeignKey(AdventureEvent, on_delete=models.CASCADE)
    start_point = models.CharField(max_length=70, null=True)
    destination = models.CharField(max_length=70, null=True)

    def __str__(self):
        return "BookedEventFrom- " + str(self.booked_event)


class TouristReview(models.Model):
    tourist_id = models.ForeignKey(User, on_delete=models.CASCADE, )
    adventureevent = models.ForeignKey(AdventureEvent, on_delete=models.CASCADE)
    tourist_review = models.CharField(max_length=256)

    def __str__(self):
        return str(self.tourist_id)

AdventureClub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import AdventureClub, AdventureEvent


class clubRegisterationForm(forms.ModelForm):
    owner = forms.CharField.widget(attrs={'readonly': 'true'})

    class Meta:
        model = AdventureClub
        fields = '__all__'
        exclude = ('owner', 'featured',)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class DateInput(forms.DateInput):
    input_type = 'date'


class adventureEventform(forms.ModelForm):
    class Meta:
        model = AdventureEvent
        exclude = ('event_by','featured',)
        fields = '__all__'
        widgets = {
            'event_start_date': DateInput(),
            'event_end_date': DateInput(),
        }

AdventureClub/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.urls import reverse_lazy
from . import models
from .forms import clubRegisterationForm, SignUpForm, adventureEventform
from django.views.generic.edit import DeleteView, UpdateView


# Create your views here.

def index(request):
    cities = models.AdventureClub.objects.values('city')
    clubs = ''
    featuredClubs = models.AdventureClub.objects.filter(featured=True)
    featuredEvents = models.AdventureEvent.objects.filter(featured=True)
    if request.method == 'POST':
        query = request.POST.get('city')
        clubs = models.AdventureClub.objects.filter(city=query)
    context = {'user': request.user, 'city': cities, 'club': clubs, 'FC': featuredClubs, 'FE': featuredEvents}
    return render(request, 'AdventureClubs/index.html', context)


def popedEvent(request, pk):
    poppedEvent = models.AdventureEvent.objects.filter(id=pk)
    context = {'pop': poppedEvent}
    return render(request, 'AdventureClubs/index.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('club:signIn')
    else:
        form = SignUpForm()
    context = {'form': form}
    return render(request, 'AdventureClubs/signUp.html', context)


def signIn(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user, backend=None)
                    messages.info(request, f"You are now logged in as {username}")
                    return HttpResponseRedirect('/club/')
            else:
                form = AuthenticationForm()
                msg = "Incorrect username or password!"
                return render(request, 'AdventureClubs/SignIn.html', context={'msg': msg, 'form': form})
                # return redirect('club:signIn')
        else:
            form = AuthenticationForm()
            return render(request, 'AdventureClubs/SignIn.html', context={'form': form})
    else:
        return HttpResponseRedirect('/club/index/')


def signOut(request):
    logout(request)
    return redirect('club:signIn')


def RegisterClub(request):
    if request.method == 'POST':
        form = clubRegisterationForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.owner = request.user
            form.save()
            messages.success(request, 'Your adventure club is registered successfully!')
    form = clubRegisterationForm()
    return render(request, 'AdventureClubs/registerClub.html', context={'form': form, })


def createEvent(request):
    clubs = models.AdventureClub.objects.filter(owner=request.user)
    if request.method == 'POST':
        form = adventureEventform(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            club = request.POST.get('club')
            # club_rec = models.AdventureClub.objects.filter(club_name=club).values(models.AdventureClub.pk)
            # club_rec = models.AdventureClub.objects.get(club_name=club)
            # print("Club Id", club_rec.pk)
            # form = form.save(commit=False)
            # form.event_by = club_rec.pk
            # form.save()
            # ev_by = club
            # club_ref = models.AdventureClub.objects.get(id=models.AdventureClub.objects.filter(club_name=club))
            # print(club_ref)
            # models.AdventureEvent.event_by = club_rec.pk
            title = form.cleaned_data['title']
            overview = form.cleaned_data['overview']
            image = form.cleaned_data['image']
            event_start_date = form.cleaned_data['event_start_date']
            event_end_date = form.cleaned_data['event_end_date']
            eventmodelobj = models.AdventureEvent(event_by=models.AdventureClub.objects.get(club_name=club), title=title
                                                  , overview=overview, image=image
                                                  , event_start_date=event_start_date, event_end_date=event_end_date)
            eventmodelobj.save()
            messages.success(request, 'Event is created successfully!')
    form = adventureEventform()
    return render(request, 'AdventureClubs/adventureevent_form.html', context={'form': form, 'clubs': clubs, })


def home(request):
    return render(request, 'AdventureClubs/home.html')


def myClubs(request):
    userClub = models.AdventureClub.objects.filter(owner=request.user)
    return render(request, "AdventureClubs/myClubs.html", context={'clubs': userClub})


def onGoingEvents(request):
    events = models.AdventureEvent.objects.all()
    return render(request, "AdventureClubs/events.html", context={'event': events})


def searchResults(request):
    queryset = models.AdventureEvent.objects.all()
    query = request.GET.get('city')
    print("--------------------------------------------", query)
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)

        ).distinct()

    context = {
        'FE': queryset
    }
    return render(request, 'AdventureClubs/search_results.html', context)


def clubDetail(request, pk):
    obj = models.AdventureClub.objects.filter(id=pk)
    obj1 = models.AdventureEvent.objects.filter(event_by=pk)
    context = {'fc': obj, 'fe': obj1}
    return render(request, 'AdventureClubs/clubDetail.html', context)


class deleteClub(DeleteView):
    model = models.AdventureClub
    success_url = reverse_lazy('club:myClubs')
    template_name = 'AdventureClubs/adventureclub_confirm_delete.html'


class updateClub(UpdateView):
    model = models.AdventureClub
    fields = ('club_name', 'contact', 'email', 'club_image', 'club_address', 'city')
    success_url = reverse_lazy('club:myClubs')
    template_name = 'AdventureClubs/registerClub.html'

AdventureClub/templates/AdventureClubs/adventureclub_confirm_delete.html
{% extends 'AdventureClubs/base.html' %}
{% block body_block %}
<div class="container d-flex justify-content-center" style="margin-top:100px;">
    <form method="post" class=" jumbotron">
        {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-outline-danger" type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

AdventureClub/templates/AdventureClubs/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Sayahat</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/bootstrap4/bootstrap.min.css' %}"
    />
    <link
      href="{%static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'plugins/OwlCarousel2-2.2.1/animate.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'styles/main_styles.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'styles/responsive.css'%}"
    />
    <!--	////-->
    <link rel="stylesheet" type="text/css" href="{%static 'styles/all.css'%}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <!--////-->

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script>
      setTimeout(function () {
        if ($("#msg").length > 0) {
          $("#msg").remove();
        }
      }, 3000);
    </script>
    <style>
		.alert {
			width: 100%;
		}
		#top-alert {

		position: fixed;
		margin-top: 100px;
		z-index: 99999;
		}
      #mylink {
        text-decoration: none;
      }
      .alert.alert-server {
        margin-bottom: 0;
        border-radius: 0;
      }
    </style>
  </head>
  <body>
    <!-- Header -->

    <header class="header bg-dark" style="position: fixed">
      <div class="container">
        <div class="row">
          <div class="col">
            <div
              class="header_content d-flex flex-row align-items-center justify-content-start"
            >
              <div
                class="header_content_inner d-flex flex-row align-items-end justify-content-start"
              >
                <div class="logo">
                  <a id="mylink" href="{%url 'club:index'%}"
                    >Sayahat Adventure Clubs</a
                  >
                </div>
                <nav class="main_nav" id="navbarNavDropdown">
                  <ul
                    class="d-flex flex-row align-items-start justify-content-start"
                  >
                    <li><a id="mylink" href="{%url 'club:index'%}">Home</a></li>
                    {%if user.is_authenticated%}
                    <li>
                      <a id="mylink" href="{%url 'club:register'%}"
                        >Register Club</a
                      >
                    </li>
                    <li>
                      <a id="mylink" href="{%url 'club:myClubs'%}">My Clubs</a>
                    </li>
                    <li>
                      <a id="mylink" href="{%url 'club:createEvent'%}"
                        >Create Event</a
                      >
                    </li>
                    <li>
                      <a id="mylink" href="{%url 'club:signOut'%}">Logout</a>
                    </li>
                    {%else%}
                    <li>
                      <a id="mylink" href="{%url 'club:events'%}">Events</a>
                    </li>
                    <li>
                      <a id="mylink" href="{%url 'club:signIn'%}">SignIn</a>
                    </li>
                    <li>
                      <a id="mylink" href="{%url 'club:signUp'%}">SignUp</a>
                    </li>
                    {%endif%}
                  </ul>
                </nav>
                <!--							<div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>-->

                <!-- Hamburger -->

                <div class="hamburger ml-auto">
                  <i class="fa fa-bars" aria-hidden="true"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
    </header>
	<!-- for popup message
	<div class="alert alert-danger alert-server" role="alert">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{% block msg %}{% endblock %}</strong>
      </div> -->

    <!-- Menu -->

    <div class="menu">
      <div
        class="menu_header d-flex flex-row align-items-center justify-content-start"
      >
        <div class="menu_logo"><a href="index.html">Sayahat</a></div>
        <div class="menu_close_container ml-auto">
          <div class="menu_close">
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
      <div class="menu_content">
        <ul>
          <li><a id="mylink" href="{%url 'club:index'%}">Home</a></li>
          {%if user.is_authenticated%}
          <li>
            <a id="mylink" href="{%url 'club:register'%}">Register Club</a>
          </li>
          <li><a id="mylink" href="{%url 'club:myClubs'%}">My Clubs</a></li>
          <li>
            <a id="mylink" href="{%url 'club:createEvent'%}">Create Event</a>
          </li>
          <li><a id="mylink" href="{%url 'club:signOut'%}">Logout</a></li>
          {%else%}
          <li><a id="mylink" href="{%url 'club:events'%}">Events</a></li>
          <li><a id="mylink" href="{%url 'club:signIn'%}">SignIn</a></li>
          <li><a id="mylink" href="{%url 'club:signUp'%}">SignUp</a></li>
          {%endif%}
        </ul>
      </div>
      <div class="menu_social">
        <div class="menu_phone ml-auto">Call us: 00-56 445 678 33</div>
        <ul class="d-flex flex-row align-items-start justify-content-start">
          <li>
            <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a>
          </li>
        </ul>
      </div>
    </div>

    {% block body_block %} {% endblock %} 
	{% include 'AdventureClubs/footer.html'%}

    <script src="{%static 'js/jquery-3.2.1.min'%}"></script>
    <script src="{%static 'styles/bootstrap4/popper.js'%}"></script>
    <script src="{%static 'styles/bootstrap4/bootstrap.min.js'%}"></script>
    <script src="{%static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
    <script src="{%static 'plugins/Isotope/isotope.pkgd.min.js'%}"></script>
    <script src="{%static 'plugins/scrollTo/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'plugins/easing/easing.js'%}"></script>
    <script src="{%static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
    <script src="{%static 'js/custom.js'%}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

AdventureClub/templates/AdventureClubs/base_for_index.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sayahat</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{%static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'plugins/OwlCarousel2-2.2.1/animate.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'styles/main_styles.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'styles/responsive.css'%}">
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
	<style>
		#mylink{
			text-decoration:none;
		}
	</style>
</head>
<body>


	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
							<div class="logo"><a id="mylink" href="{%url 'club:index'%}">Sayahat Adventure Clubs</a></div>
							<nav class="main_nav " id="navbarNavDropdown">
								<ul class="d-flex flex-row align-items-start justify-content-end">
									<li><a id="mylink" href="{%url 'club:index'%}">Home</a></li>
								{%if user.is_authenticated%}
									<li><a id="mylink" href="{%url 'club:register'%}">Register Club</a></li>
									<li><a id="mylink" href="{%url 'club:myClubs'%}">My Clubs</a></li>
									<li><a id="mylink" href="{%url 'club:createEvent'%}">Create Event</a></li>
									<li><a id="mylink" href="{%url 'club:signOut'%}">Logout</a></li>
								{%else%}
									<li><a id="mylink" href="{%url 'club:events'%}">Events</a></li>
									<li><a id="mylink" href="{%url 'club:signIn'%}">SignIn</a></li>
									<li><a id="mylink" href="{%url 'club:signUp'%}">SignUp</a></li>
								{%endif%}

<!--									<li><a href="#">Services</a></li>-->
<!--									<li><a href="news.html">News</a></li>-->
<!--									<li><a href="contact.html">Contact</a></li>-->
								</ul>
							</nav>
<!--							<div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>-->

							<!-- Hamburger -->

							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
    <!-- Menu -->

	<div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">
			<div class="menu_logo"><a href="index.html">Sayahat</a></div>
			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
		<div class="menu_content">
			<ul>
				<li><a id="mylink" href="{%url 'club:index'%}">Home</a></li>
				{%if user.is_authenticated%}
					<li><a id="mylink" href="{%url 'club:register'%}">Register Club</a></li>
					<li><a id="mylink" href="{%url 'club:myClubs'%}">My Clubs</a></li>
					<li><a id="mylink" href="{%url 'club:createEvent'%}">Create Event</a></li>
					<li><a id="mylink" href="{%url 'club:signOut'%}">Logout</a></li>
				{%else%}
					<li><a id="mylink" href="{%url 'club:events'%}">Events</a></li>
					<li><a id="mylink" href="{%url 'club:signIn'%}">SignIn</a></li>
					<li><a id="mylink" href="{%url 'club:signUp'%}">SignUp</a></li>
				{%endif%}
			</ul>
		</div>
		<div class="menu_social">
			<div class="menu_phone ml-auto">Call us: 00-56 445 678 33</div>
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>

{% block body_block %}
{% endblock %}
{%include 'AdventureClubs/footer.html'%}


<script src="{%static 'js/jquery-3.2.1.min'%}"></script>
<script src="{%static 'styles/bootstrap4/popper.js'%}"></script>
<script src="{%static 'styles/bootstrap4/bootstrap.min.js'%}"></script>
<script src="{%static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
<script src="{%static 'plugins/Isotope/isotope.pkgd.min.js'%}"></script>
<script src="{%static 'plugins/scrollTo/jquery.scrollTo.min.js'%}"></script>
<script src="{%static 'plugins/easing/easing.js'%}"></script>
<script src="{%static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
<script src="{%static 'js/custom.js'%}"></script>
</body>
</html>

AdventureClub/templates/AdventureClubs/password_reset_complete.html
{% extends 'AdventureClubs/base.html' %}
{% block body_block %}
<div class="container shadow jumbotron bg-white" style="margin-top:200px;margin-bottom:150">
    <h2 class="text-success"> Congrats. The password has been changed!!! </h2>
    <h3>Do you want to login now?</h3>
    <a href="{% url 'club:signIn' %}" class="btn btn-primary">Login</a>
</div>
{% endblock %}